spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ayano2002

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  #开启确认机制
    publisher-returns: true #开启无法正常到达队列的消息的退回机制
    listener:
      simple:
        acknowledge-mode: manual   #开启手动ack

  thymeleaf:
    cache: false

  redis:
      host: 192.168.233.128
      port: 6379
      jedis:
        pool:
          max-active: 30
          max-idle: 10
          min-idle: 3
          max-wait: 3000

  mail:
    host: smtp.qq.com
    username: 2512835516@qq.com  #用自己的
    password: nzepvzbegvopeadh   # 用自己的  邮箱授权码
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.hzwn
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl